### PR TITLE
Updated rubocop rules.

### PR DESCRIPTION
**Pull request by MiguelSavignano**
add more markdown files with new rules and update with the last examples .
I use a ruby script to generate this files, but I don't know it useful the script.

### CODE REVIEW

**Comment by MiguelSavignano** [comment]
For fix test i need to add ruby file with the bad example?

**Comment by rtfpessoa** [comment]
I need to get some time to test this. But since Rubocop has that script to generate using it seems like a nice idea.
When I have more details I will comment here.

**Comment by rtfpessoa** [comment]
I think I found the problem. The json schema is not valid in `docs/patterns.json`. The parameters field needs to be an array. Check the old one for more details.

Is weird the step `$ (cd $HOME/codacy-plugins-test && sbt -Dcodacy.tests.ignore.descriptions=true "run-main codacy.plugins.DockerTest json $CIRCLE_PROJECT_REPONAME:latest")` is passing but inside it says it could not parse the json. Need to check it later. In the meanwhile if you can please update the exporter.

**Comment by rtfpessoa** [comment]
@MiguelSavignano seems like https://github.com/codacy/codacy-rubocop/blob/master/src/main/resources/docs/description/description.json is not being generated correctly since a lot of patterns are missing.

Also seems like there are some patterns that disappeared. Can you confirm we are using the rubocop version 0.51.0 of the docs?

**Comment by MiguelSavignano** [comment]
@rtfpessoa Hi Now I using the rubocop v0.51.0.
I have added the ruby script for generate yml file with al rubocop rules.

It's needed use ruby version 2.4.1 and install gems with bundle
```
bundle install
ruby src/main/ruby/rubocop_doc/generator.rb
ruby src/main/ruby/codacy/rubocop/generator.rb
```

right now my script only support one rubocop version, it is necessary the script can generate doc for any rubocop version?

**Comment by rtfpessoa** [comment]
@MiguelSavignano completely missed this message. At the moment we just need docs for one version.

Ideally we can generate the docs when creating the docker in here https://github.com/codacy/codacy-rubocop/blob/master/build.sbt#L58

Also i just noticed you are using a fixed `level` and  `category` in `patterns.json` and an empty `title` and `description` in `descriptions.json`.

At the moment for `level` we have:
* `Lint` => Warning
* `Metrics` => `Warning`
* `Performance` => `Warning`
* `Rails` => `Warning` 
* Else => `Info`

Since you seem to have added more patterns would be nice if we could check if all are making sense.

Regarding `category` we have:
* `Lint` => `ErrorProne`
* `startsWith("Metrics") && !contains("Length") && !pattern.contains("AbcSize")` => `ErrorProne`
* `Rails` => `ErrorProne`
* `Performance` => `Performance`
* `Security` => `Security`
* Else => `CodeStyle`

Regarding title and description might just be a bug in the generator, right?

Would you be interested in adding the generator to build.sbt?

To test changes just do: `sbt docker:publishLocal` or just wait for circle to create it.

**Comment by rtfpessoa** [comment]
Continued in #39

**Pull request closed without merging**
